// ─────────────────────────────────────────────────────────────
//  IMPORT X PROFILES FROM CSV
//
//  Usage:
//    node scripts/import-x-csv.mjs path/to/your-file.csv
//
//  Reads your CSV (skips the header row), maps the columns by
//  NAME (so column order doesn't matter), and writes
//  src/data/xProfiles.ts — ready to use on the Profiles page.
//
//  Expected headers (case-insensitive, exact spelling matters):
//    Name, Can Dm, Description, Followers, Location,
//    Profile Url, Avatar Url, Is Blue Verified, Created At
// ─────────────────────────────────────────────────────────────
import fs from 'node:fs';
import path from 'node:path';

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: node scripts/import-x-csv.mjs path/to/file.csv');
  process.exit(1);
}

const raw = fs.readFileSync(inputPath, 'utf8');

// Minimal CSV parser that handles quoted fields containing commas,
// quotes ("" escaping), and newlines inside quotes — the things a
// plain .split(',') breaks on the moment a description has a comma.
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  // Normalize Windows line endings so \r doesn't leak into fields.
  text = text.replace(/\r\n/g, '\n');

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\n') {
      row.push(field); field = '';
      rows.push(row); row = [];
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.some((cell) => cell.trim() !== ''));
}

const rows = parseCsv(raw);
if (rows.length < 2) {
  console.error('No data rows found (is the file empty, or just a header?).');
  process.exit(1);
}

const header = rows[0].map((h) => h.trim().toLowerCase());
const dataRows = rows.slice(1); // skip row 1 (titles), as requested

function col(headerNames) {
  for (const name of headerNames) {
    const idx = header.indexOf(name.toLowerCase());
    if (idx !== -1) return idx;
  }
  return -1;
}

const idx = {
  name: col(['Name']),
  canDm: col(['Can Dm', 'Can DM']),
  description: col(['Description']),
  followers: col(['Followers', 'Followers Count']),
  location: col(['Location']),
  profileUrl: col(['Profile Url', 'Profile URL']),
  avatarUrl: col(['Avatar Url', 'Avatar URL']),
  verified: col(['Is Blue Verified']),
  createdAt: col(['Created At']),
};

const missing = Object.entries(idx).filter(([, v]) => v === -1).map(([k]) => k);
if (missing.length) {
  console.error('Could not find these columns in row 1:', missing.join(', '));
  console.error('Found headers were:', rows[0].join(' | '));
  process.exit(1);
}

function toBool(v) {
  return /^(yes|true|y|1)$/i.test((v ?? '').trim());
}
function toNumber(v) {
  const n = Number((v ?? '').replace(/[, ]/g, ''));
  return Number.isFinite(n) ? n : 0;
}
function handleFromUrl(url) {
  const m = (url ?? '').match(/(?:x\.com|twitter\.com)\/([A-Za-z0-9_]+)/i);
  return m ? m[1] : '';
}
function escape(s) {
  return (s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, ' ').trim();
}

const profiles = dataRows
  .map((r) => ({
    name: (r[idx.name] ?? '').trim(),
    handle: handleFromUrl(r[idx.profileUrl]),
    canDm: toBool(r[idx.canDm]),
    description: (r[idx.description] ?? '').trim(),
    followers: toNumber(r[idx.followers]),
    location: (r[idx.location] ?? '').trim() || 'Other',
    profileUrl: (r[idx.profileUrl] ?? '').trim(),
    avatarUrl: (r[idx.avatarUrl] ?? '').trim(),
    isBlueVerified: toBool(r[idx.verified]),
    createdAt: (r[idx.createdAt] ?? '').trim(),
  }))
  .filter((p) => p.profileUrl); // skip blank rows

profiles.sort((a, b) => a.location.localeCompare(b.location) || a.name.localeCompare(b.name));

const body = profiles
  .map(
    (p) => `  {
    name: '${escape(p.name)}',
    handle: '${escape(p.handle)}',
    canDm: ${p.canDm},
    description: '${escape(p.description)}',
    followers: ${p.followers},
    location: '${escape(p.location)}',
    profileUrl: '${escape(p.profileUrl)}',
    avatarUrl: '${escape(p.avatarUrl)}',
    isBlueVerified: ${p.isBlueVerified},
    createdAt: '${escape(p.createdAt)}',
  },`
  )
  .join('\n');

const output = `// ─────────────────────────────────────────────────────────────
//  AUTO-GENERATED by scripts/import-x-csv.mjs — do not hand-edit.
//  Re-run the script to regenerate this file from your CSV.
//  Generated: ${new Date().toISOString()}
// ─────────────────────────────────────────────────────────────
export type XProfile = {
  name: string;
  handle: string;
  canDm: boolean;
  description: string;
  followers: number;
  location: string;
  profileUrl: string;
  avatarUrl: string;
  isBlueVerified: boolean;
  createdAt: string;
};

export const xProfiles: XProfile[] = [
${body}
];
`;

const outPath = path.join(process.cwd(), 'src/data/xProfiles.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, output, 'utf8');

console.log(`Wrote ${profiles.length} profile(s) to src/data/xProfiles.ts`);
const locations = [...new Set(profiles.map((p) => p.location))].sort();
console.log('Locations found:', locations.join(', '));
